version: "3.8"
services:
  server:
    build: ./server
    container_name: dockercc22sp-server
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: dockercc22sp-client
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    